import Head from "next/head";
import LandingPage from "./LandingPage";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LandingPage />
    </div>
  );
}
